name: PlayerCollars
version: 1.0.0
main: com.dentoper.playercollars.PlayerCollarsPlugin
description: Collar system for players
authors: [dentoper]
api-version: "1.21"

commands:
  collar:
    description: Collar management
    usage: /collar help
    aliases: [collars]

permissions:
  playercollars.use:
    description: Use collars
    default: true
  playercollars.collar.standard:
    description: Standard collar
    default: true
  playercollars.collar.leather:
    description: Leather collar
    default: op
  playercollars.collar.gold:
    description: Gold collar
    default: op
  playercollars.collar.diamond:
    description: Diamond collar
    default: op
  playercollars.admin:
    description: Admin commands
    default: op
