name: SmartHarvestPlus
version: 1.0.0
main: com.dentoper.smartharvest.SmartHarvestPlus
description: Smart farming plugin for Minecraft Paper 1.21 - auto-harvest and replant crops
authors: [dentoper]
api-version: "1.21"

commands:
  smartharvest:
    description: SmartHarvestPlus main command
    usage: /smartharvest help
    aliases: [sh]
  sh:
    description: SmartHarvestPlus alias command
    usage: /sh help

permissions:
  smartharvest.use:
    description: Use SmartHarvestPlus features
    default: true
  smartharvest.gui:
    description: Open SmartHarvestPlus GUI
    default: true
  smartharvest.admin:
    description: Admin commands (reload)
    default: op
